<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
<script type="text/javascript" src="{{asset('client/js/libs/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('client/js/libs/jquery.fancybox.js')}}"></script>
<script type="text/javascript" src="{{asset('client/js/libs/jquery-ui.min.js')}}"></script>
<script type="text/javascript" src="{{asset('client/js/libs/owl.carousel.js')}}"></script>
<script type="text/javascript" src="{{asset('client/js/libs/jquery.mCustomScrollbar.js')}}"></script>
<script type="text/javascript" src="{{asset('client/js/libs/wow.js')}}"></script>
<script type="text/javascript" src="{{asset('client/js/libs/popup.js')}}"></script>
<script type="text/javascript" src="{{asset('client/js/theme.js')}}"></script>